#!/bin/bash
echo "=== Checking TODO locations - Generated vs Manual Files ==="
echo ""
echo "1. FILES IN BUILD/GENERATED DIRECTORIES (Auto-generated):"
echo "========================================================="
grep -r "TODO" --include="*.kt" app/build/generated/ 2>/dev/null | wc -l
echo "TODOs found in generated files"
echo ""
echo "Sample generated files with TODOs:"
find app/build/generated -name "*.kt" -exec grep -l "TODO" {} \; 2>/dev/null | head -5

echo ""
echo "2. FILES IN SRC DIRECTORIES (Your manual code):"
echo "================================================"
grep -r "TODO" --include="*.kt" app/src/ 2>/dev/null | wc -l
echo "TODOs found in your source files"
echo ""
echo "Your files with TODOs:"
find app/src -name "*.kt" -exec grep -l "TODO" {} \; 2>/dev/null

echo ""
echo "=== Checking OpenAPI Generator markers ==="
echo "Files with 'auto generated by OpenAPI' header:"
find app/build/generated -name "*.kt" -exec grep -l "auto generated by OpenAPI" {} \; 2>/dev/null | wc -l
echo "auto-generated files found"

echo ""
echo "=== Detailed look at AuraAIServiceImpl.kt ==="
echo "Location: app/src/main/java/dev/aurakai/auraframefx/ai/AuraAIServiceImpl.kt"
echo "Is this file auto-generated?"
grep -c "auto generated" app/src/main/java/dev/aurakai/auraframefx/ai/AuraAIServiceImpl.kt 2>/dev/null || echo "0"
echo "(0 = No, it's your manual code | >0 = Yes, it's generated)"

echo ""
echo "=== Summary of TODO distribution ==="
echo "Generated directories:"
find app/build -type d -name "generated" 2>/dev/null | head -5
echo ""
echo "Your source directories:"
find app/src -type d -maxdepth 3 2>/dev/null | grep -v "/build/" | head -10

echo ""
echo "=== Quick TODO count verification ==="
echo "Total .kt files in src:"
find app/src -name "*.kt" 2>/dev/null | wc -l
echo "Total .kt files in build/generated:"
find app/build/generated -name "*.kt" 2>/dev/null | wc -l
